spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: qsc13579
    #    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall     #底层功能开启，stat(sql监控)，wall（防火墙）
      stat-view-servlet:  #监控页的开启
        enabled: true
      web-stat-filter:   #监控web
        enabled: true
        url-pattern: /*
        exclusions:
  jdbc:
    template:
      query-timeout: 10

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml